### ISSUE TITLE
Global minor mode

### ISSUE THREAD

**Issue by progfolio** [mrmekon/snitch-el#1]
Feature suggestion: make this a global minor mode which a user can toggle in the usual way instead of calling the init/deinit commands.

**Comment by mrmekon** [comment]
Sure, that sounds reasonable.

I originally didn't do that because I think of minor modes as relating to buffers in some way, which snitch does not... but if menu bar/toolbar/scrollbar are minor modes, I suppose snitch can be too.

Is there any advantage to it other than a more standard name for the function that starts it?

**Comment by mrmekon** [comment]
Done!  With configurable mode-line text and init/de-init hooks.
